// Smart Contract Configuration
// Generated by setup script on 2025-07-05T09:29:08.381Z

module.exports = {
    "CONTRACT_ADDRESS": "0x1A06E49FEe9b9bbC9aD546bbF6043dfa7E6941f4",
    "PRIVATE_KEY": "0d4b8590f2fefbd23179eebe9935915813f08e144d94d4485ef3b8b1242fa1e4",
    "RPC_URL": "https://eth-sepolia.g.alchemy.com/v2/ywJs2Qqr_ncoGBPXeXMHIekKPC8Ty-_o",
    "NETWORK": {
        "name": "Sepolia Testnet",
        "chainId": 11155111,
        "currency": "ETH"
    },
    "GAS_SETTINGS": {
        "gasLimit": 500000,
        "gasPrice": null
    }
};